#!/bin/sh

# Super+Q to close the focused view
riverctl map normal Super D close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+F to toggle fullscreen
riverctl map normal Super Space toggle-fullscreen

# Super+F to spawn firefox
riverctl map normal Super F spawn 'firefox'

# Super+E to spawn emacs
riverctl map normal Super E spawn "emacs -bg black"

# Super+Return to spawn terminal 
riverctl map normal Super Return spawn 'alacritty'

# Super+P to spawn rofi run
riverctl map normal Super P spawn 'rofi -show drun -show-icons'

# Multimedia keys
riverctl map normal Super comma spawn 'cmus-remote -r'
riverctl map normal Super period spawn 'cmus-remote -n'
riverctl map normal Super slash spawn '~/.config/scripts/cmus-play-pause.sh'

# Content
riverctl map normal Super B spawn '~/.config/scripts/dmenu-books.clj'
riverctl map normal Super V spawn '~/.config/scripts/dmenu-videos.clj'

# Set background and border color
riverctl background-color 0x101010
riverctl border-color-focused 0x8893a9
riverctl border-color-unfocused 0x4b5467
riverctl border-width 0

# Set keyboard repeat rate
riverctl set-repeat 45 200

# Hide cursor after n ms.
riverctl hide-cursor timeout 3000

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 0 & dunst & waybar &
